export const WINE_LIST = [
  {
    title: 'tinto',
    items: [
      {
        id: 1,
        name: 'Amadeo',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/tinto%20amadeo.png?raw=true',
        price: 160,
        description:'Com 80% da sua produção exportada para o exterior, a Finca Amadeo se tornou um encanto para os enófilos brasileiros, sempre focado na sua qualidade e preços competitivos, além de apresentar uma grande diversidade de rótulos no mercado.',
      },
      {
        id: 2,
        name: 'Cabos Bramare',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/tinto%20cabos%20bramare.png?raw=true',
        price: 165,
        description:'Trata-se de um tinto estruturado, com taninos arredondados, sensação de cremosidade no paladar, e que expressa aromas de especiarias como baunilha e pimenta vermelha.',
      },
      {
        id: 3,
        name: 'Cartuxa',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/tinto%20cartucxa%20ea2021.png?raw=true',
        price: 210,
        description:'Este vinho de cor granada possui um aroma de fruto jovem e fresco, com boa densidade e notas de vegetal seco. Na boca, é macio, com uma ligeira adstringência, característica da juventude. Apresenta bons taninos, estando pronto para beber.',
      },
      {
        id: 4,
        name: 'Castelo di Quercetto',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/tinto%20castelo%20di%20quercetto.png?raw=true',
        price: 225,
        description:'Este vinho é um clássico da região de Chianti, na Toscana, Itália, por esse motivo são marcados com Clássico no rótulo. E como o seu armazenamento é feito em barril extra ainda é nomeiado como riserva ao seu título. Produzido com uvas sangiovese, que são colhidas a mão e passam por um rigoroso processo de seleção, resultando em um vinho de alta qualidade.',
      },
      {
        id: 5,
        name: 'Catena Zapata',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/tinto%20catena%20zapata.png?raw=true',
        price: 188,
        description:'O Malbec Argentino é elaborado com um corte de vinhas antigas de dois icônicos vinhedos da família Catena Zapata: Nicasia e Angélica. Cada parcela é colhida individualmente, em seu ponto ideal, e vinificada separadamente. ',
      },
      {
        id: 6,
        name: 'Cloudy Bay',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/tinto%20cloud%20bay.png?raw=true',
        price: 149,
        description:'A produção é realizada em Marlborough no extremo norte da ilha do sul da Nova Zelândia. Livre de drenagem com solos ricos em nutrientes clima marítimo e horas de luz solar a região de Marlborough é única pelo seu terroir ideal para a vinificação.',
      },
      {
        id: 7,
        name: 'Terezas de Los Andes',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/tinto%20miniterrazas.png?raw=true',
        price: 118,
        description:'Possui notas florais e frutadas intensas. Revela um caráter tostado e picante da pimenta preta e cravinho. Seu paladar doce e suculento entregam finesse, taninos delicados e um elegante acabamento de frutas negras.',
      },
      {
        id: 8,
        name: 'Vegano Montgras',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/tinto%20vegano%20montgras.png?raw=true',
        price: 198,
        description:'',
      },     
    ],
  },
  {
    title: 'rose',
    items: [
      {
        id: 9,
        name: 'Aliança Brut',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/rose%20alianca%20brut.png?raw=true',
        price: 220,
        description:'',
      },
      {
        id: 10,
        name: "Chateau D'esclans",
        imageUrl: "https://github.com/AndersonSantosFernandes/wineList/blob/main/rose%20chateau%20d'esclans.png?raw=true",
        price: 280,
        description:'',
      },
      {
        id: 11,
        name: 'Chateau de la Coste',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/rose%20chateau%20la%20coste.png?raw=true',
        price: 110,
        description:'',
      },
      {
        id: 12,
        name: 'Latitud 33 Malbec',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/rose%20latitud%2033%20malbec.png?raw=true',
        price: 160,
        description:'',
      },
      {
        id: 13,
        name: 'Magnum Chateau',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/rose%20magnum%20chateau.png?raw=true',
        price: 190,
        description:'',
      },
      {
        id: 14,
        name: 'Moet e Chandon',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/rose%20moet%20e%20chndon%20ice.png?raw=true',
        price: 360,
        description:'',
      },
      {
        id: 15,
        name: 'Pony Grenache',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/rose%20pony%20grenache.png?raw=true',
        price: 390,
        description:'',
      },
      {
        id: 16,
        name: 'Salentino Rosato',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/rose%20salentino%20rosato.png?raw=true',
        price: 210,
        description:'',
      },
      {
        id: 17,
        name: 'Salton Evidence',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/rose%20salton%20evidence.png?raw=true',
        price: 181,
        description:'',
      },
      {
        id: 18,
        name: 'Veuve Cliquol',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/rose%20veuve%20clicqut%20ice.png?raw=true',
        price: 310,
        description:'',
      },
    ],
  },
  {
    title: 'espumante',
    items: [    
      {
        id: 19,
        name: 'Cerro da Cruz',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/espumante%20cerro%20da%20cruz%20nature.png?raw=true',
        price: 210,
        description:'',
      },
      {
        id: 20,
        name: 'Magno Extra',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/espumante%20magno%20extra.png?raw=true',
        price: 270,
        description:'',
      },
      {
        id: 21,
        name: 'Salton Domenico',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/espumante%20salton%20domenico.png?raw=true',
        price: 210,
        description:'',
      },
      {
        id: 22,
        name: 'Vertice Brut',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/espumante%20vertice%20brut.png?raw=true',
        price: 110,
        description:'',
      },
      {
        id: 23,
        name: 'Vertice Pinot',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/espumante%20vertice%20pinot.png?raw=true',
        price: 150,
        description:'',
      },
    ],
  },
  {
    title: 'branco',
    items: [     
      {
        id: 24,
        name: 'Chandon Excelence',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/branco_chandon%20excelence.png?raw=true',
        price: 380,
        description:'',
      },
      {
        id: 25,
        name: 'Dom Perignon',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/branco_dom%20perignon.png?raw=true',
        price: 299,
        description:'',
      },
      {
        id: 26,
        name: 'Serro da Cruz',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/branco_serro%20da%20cruz.png?raw=true',
        price: 210,
        description:'',
      },
      {
        id: 27,
        name: 'Terrazas de los Andes',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/branco_tereza%20de%20los%20andes.png?raw=true',
        price: 210,
        description:'',
      },
      {
        id: 28,
        name: 'Vegano Freixenet',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/branco_vegano%20freixenet.png?raw=true',
        price: 318,
        description:'',
      },
    ],
  },
  {
    title: 'verde',
    items: [     
      {
        id: 29,
        name: 'Cabo da Roca',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/verde%20cabo%20da%20roca%20loureiro.png?raw=true',
        price: 218,
        description:'',
      },
      {
        id: 30,
        name: 'Cabo da Roca Verdelho',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/verde%20cabo%20da%20roca%20verdelho.png?raw=true',
        price: 318,
        description:'',
      },
      {
        id: 31,
        name: 'Moscato Limão Siciliano',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/verde%20moscato%20limao%20siciliano.png?raw=true',
        price: 318,
        description:'',
      },
    ],
  },
];