export const WINE_LIST = [
  {
    title: 'tinto',
    items: [
      {
        id: 0,
        name: 'Amadeo',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/tinto%20amadeo.png?raw=true',
        price: 160,
        description:'Com 80% da sua produção exportada para o exterior, a Finca Amadeo se tornou um encanto para os enófilos brasileiros, sempre focado na sua qualidade e preços competitivos, além de apresentar uma grande diversidade de rótulos no mercado.',
      },
      {
        id: 1,
        name: 'Cabos Bramare',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/tinto%20cabos%20bramare.png?raw=true',
        price: 165,
        description:'Trata-se de um tinto estruturado, com taninos arredondados, sensação de cremosidade no paladar, e que expressa aromas de especiarias como baunilha e pimenta vermelha.',
      },
      {
        id: 2,
        name: 'Cartuxa',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/tinto%20cartucxa%20ea2021.png?raw=true',
        price: 210,
        description:'Este vinho de cor granada possui um aroma de fruto jovem e fresco, com boa densidade e notas de vegetal seco. Na boca, é macio, com uma ligeira adstringência, característica da juventude. Apresenta bons taninos, estando pronto para beber.',
      },
      {
        id: 3,
        name: 'Castelo di Quercetto',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/tinto%20castelo%20di%20quercetto.png?raw=true',
        price: 225,
        description:'Este vinho é um clássico da região de Chianti, na Toscana, Itália, por esse motivo são marcados com Clássico no rótulo. E como o seu armazenamento é feito em barril extra ainda é nomeiado como riserva ao seu título. Produzido com uvas sangiovese, que são colhidas a mão e passam por um rigoroso processo de seleção, resultando em um vinho de alta qualidade.',
      },
      {
        id: 4,
        name: 'Catena Zapata',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/tinto%20catena%20zapata.png?raw=true',
        price: 188,
        description:'O Malbec Argentino é elaborado com um corte de vinhas antigas de dois icônicos vinhedos da família Catena Zapata: Nicasia e Angélica. Cada parcela é colhida individualmente, em seu ponto ideal, e vinificada separadamente. ',
      },
      {
        id: 5,
        name: 'Cloudy Bay',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/tinto%20cloud%20bay.png?raw=true',
        price: 149,
        description:'A produção é realizada em Marlborough no extremo norte da ilha do sul da Nova Zelândia. Livre de drenagem com solos ricos em nutrientes clima marítimo e horas de luz solar a região de Marlborough é única pelo seu terroir ideal para a vinificação.',
      },
      {
        id: 6,
        name: 'Terezas de Los Andes',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/tinto%20miniterrazas.png?raw=true',
        price: 118,
        description:'Possui notas florais e frutadas intensas. Revela um caráter tostado e picante da pimenta preta e cravinho. Seu paladar doce e suculento entregam finesse, taninos delicados e um elegante acabamento de frutas negras.',
      },
      {
        id: 7,
        name: 'Vegano Montgras',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/tinto%20vegano%20montgras.png?raw=true',
        price: 198,
        description:'Possui textura agradável com corpo médio e taninos suculentos que combinam muito bem com os seus sabores frutados aliados a uma acidez equilibrada e saborosas notas de café no final.',
      },     
    ],
  },
  {
    title: 'rose',
    items: [
      {
        id: 8,
        name: 'Aliança Brut',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/rose%20alianca%20brut.png?raw=true',
        price: 220,
        description:'Elaborado com as variedades Chardonnay e Pinot Noir, pelo método Charmat, esse exemplar colore o ambiente com seu tom rosa brilhante intenso e perlage fina e persistente.',
      },
      {
        id: 9,
        name: "Chateau D'esclans",
        imageUrl: "https://github.com/AndersonSantosFernandes/wineList/blob/main/rose%20chateau%20d'esclans.png?raw=true",
        price: 280,
        description:'Feito de Grenache, Cinsault e Rolle (Vermentino), sua cor pálida é agradável aos olhos e atrai um dentro. O perfil de sabor gratificante é completo e exuberante enquanto é seco com um acabamento suave.',
      },
      {
        id: 10,
        name: 'Chateau de la Coste',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/rose%20chateau%20la%20coste.png?raw=true',
        price: 110,
        description:'O Vinho Rosé Château La Coste apresenta uma bela cor pêssego clara e brilhante, com reflexos dourados, enquanto no nariz revela aromas de frutas brancas, frutas cítricas, pêssego de videira e pêra, complementados por notas de frutas vermelhas. Na boca volumoso, ainda que macio e redondo, com um final refrescante.',
      },
      {
        id: 11,
        name: 'Latitud 33 Malbec',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/rose%20latitud%2033%20malbec.png?raw=true',
        price: 160,
        description:'Expressa aromas frutados e intensos de framboesa, cereja, morangos e ameixa vermelha com notas florais sutis. Ideal para acompanhar com canapés, brusquetas, ceviches e peixes em molhos leves.',
      },
      {
        id: 12,
        name: 'Magnum Château D’Esclans Whispering Angel',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/rose%20magnum%20chateau.png?raw=true',
        price: 190,
        description:'Possui textura macia e equilibrada, com uma acidez integrada que realça o caráter frutado do vinho. Sabores de frutas vermelhas maduras, como cerejas e morangos, toques cítricos e uma leve mineralidade.',
      },
      {
        id: 13,
        name: 'Moët & Chandon Ice Impérial Rosé',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/rose%20moet%20e%20chndon%20ice.png?raw=true',
        price: 360,
        description:'Possui aroma de frutas vermelhas, como cereja, e com delicadas notas de figo. No paladar, é cremoso, frutado, com boa acidez e doçura presente.',
      },
      {
        id: 14,
        name: 'Pink Pony Grenache',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/rose%20pony%20grenache.png?raw=true',
        price: 390,
        description:'O Pink Pony Grenache é um vinho rosé que chama a atenção desde o primeiro momento pela sua cor rosa pálida e delicada. Ao aproximar o nariz da taça, é possível sentir uma explosão de aromas frescos e frutados, com destaque para as notas de frutas vermelhas, como morangos, framboesas e cerejas.',
      },
      {
        id: 15,
        name: 'Salentino Rosato',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/rose%20salentino%20rosato.png?raw=true',
        price: 210,
        description:'Com uma cor rosa claro e brilhante, este vinho encanta com suas notas de violeta, cereja e rosa, harmonizadas com aromas envolventes de romã, framboesa e morango. Na boca, surpreende com sua leveza e frescor, apresentando uma sensação salgada, marinha e mineral que aguça os sentidos.',
      },
      {
        id: 16,
        name: 'Salton Évidence Cuvée Brut Rosé',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/rose%20salton%20evidence.png?raw=true',
        price: 181,
        description:'Elaborado a partir das variedades de uvas Chardonnay e Pinot Noir, o espumante Salton Évidence encanta por sua cor, em tons de cereja, delicada e vivaz. Enquanto seus aromas combinam frutas vermelhas frescas e maduras, com um toque de pão tostado e mel. Um espumante cremoso, de sabor marcante e com suave persistência.',
      },
      {
        id: 17,
        name: 'Veuve Clicquot Ice Jacket Brut',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/rose%20veuve%20clicqut%20ice.png?raw=true',
        price: 310,
        description:'Feito com uvas cuidadosamente selecionadas, revela uma cor rosa brilhante e um aroma intenso de frutas vermelhas maduras, como morangos e framboesas, complementadas por notas florais sutis. Seu sabor é fresco e equilibrado, com uma acidez refrescante e uma elegante efervescência.',
      },
    ],
  },
  {
    title: 'espumante',
    items: [    
      {
        id: 18,
        name: 'Cerro da Cruz Nature',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/espumante%20cerro%20da%20cruz%20nature.png?raw=true',
        price: 210,
        description:'De coloração rosé pêssego pálido e borbulhas delicadas, exibe uma perlage fina e persistente. Este espumante possui uma personalidade marcante, com uma acidez vibrante e uma textura cremosa que e com aroma intenso e fresco, destacando-se por notas florais, cítricas de maçã, cerejas frescas e sutis toques de brioches.',
      },
      {
        id: 19,
        name: 'Magno Extra Dry',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/espumante%20magno%20extra.png?raw=true',
        price: 270,
        description:'Ao provar, é possível notar a acidez refrescante e um sabor frutado que é muito agradável. As notas de frutas vermelhas e cítricas se destacam, junto com um toque de brioche que adiciona uma nota adicional de complexidade e elegância ao sabor.',
      },
      {
        id: 20,
        name: 'Domenico Salton Giornata',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/espumante%20salton%20domenico.png?raw=true',
        price: 210,
        description:'Bem feito em seu estilo vinoso, de maior sensação de dulçor e de frutas brancas e de caroço de perfil mais maduro, tem acidez refrescante e textura firme e cremosa, que trazem sustentação e equilíbrio ao conjunto, conferindo fluidez ao vinho.',
      },
      {
        id: 21,
        name: 'Vertice Brut',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/espumante%20vertice%20brut.png?raw=true',
        price: 110,
        description:'Mais uma ótima safra desse rosé, que esbanja frutas brancas e vermelhas de perfil mais fresco acompanhadas de notas florais, de ervas, de fermento e de especiarias doces, com sua acidez elétrica e sua textura firme e cremosa conferindo equilíbrio ao conjunto.',
      },
      {
        id: 22,
        name: 'Vértice Pinot Noir',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/espumante%20vertice%20pinot.png?raw=true',
        price: 150,
        description:'Um espumante monocasta, de cor leve, com bolha muito fina e elegante. Na boca, é fresco e com acidez vivificante, deixando um sabor requintado e prolongado.',
      },
    ],
  },
  {
    title: 'branco',
    items: [     
      {
        id: 23,
        name: 'Chandon Excelence Brut',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/branco_chandon%20excelence.png?raw=true',
        price: 380,
        description:'Seu aroma lembra cítricos cristalizados, ameixa preta, amêndoas, especiarias e pão tostado. O paladar começa por um franco ataque de acidez e termina com um final persistente de frutas secas.',
      },
      {
        id: 24,
        name: 'Dom Pérignon Blanc Vintage ',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/branco_dom%20perignon.png?raw=true',
        price: 299,
        description:'Fresco, cristalino e penetrante, o primeiro nariz revela um mundo vegetal e aquático únicos com sugestões de pimenta branca e gardênia. Frutas cristalizadas, com notas de tosta, de fermento, nuts e floral, com toque de alcaçuz. A maturidade do vinho se apresenta através de toques de turfa.',
      },
      {
        id: 25,
        name: 'Serro da Cruz Nature',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/branco_serro%20da%20cruz.png?raw=true',
        price: 210,
        description:'Ao degustar, percebe-se a nitidez e intensidade aromática, com notas florais, cítricas de maçã verde e pera madura, e sutis toques de panificação. Em boca, a acidez equilibrada se harmoniza perfeitamente com a untuosidade, ressaltando os aromas e proporcionando um final persistente e agradável.',
      },
      {
        id: 26,
        name: 'Terrazas de Los Andes Chardonnay',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/branco_tereza%20de%20los%20andes.png?raw=true',
        price: 210,
        description:'Este vinho Argentino possui coloração amarelo-claro, aroma de frutas amarelas, cítrico, baunilha. Na boca possui acidez agradável, frutado, leve amadeirado.',
      },
      {
        id: 27,
        name: 'Vegano Freixenet Prosecco',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/branco_vegano%20freixenet.png?raw=true',
        price: 318,
        description:'No aroma, o Freixenet Prosecco DOC Seco cativa com notas cítricas e florais, destacando-se nuances de limão siciliano, maçã verde e flores brancas. Essa combinação perfumada traz uma sensação refrescante e convida a cada gole.',
      },
    ],
  },
  {
    title: 'verde',
    items: [     
      {
        id: 28,
        name: 'Cabo da Roca Verde Doc',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/verde%20cabo%20da%20roca%20loureiro.png?raw=true',
        price: 218,
        description:'Cor verde limão. Aroma de maçã verde e groselha com notas cítricas. Levemente arejado, destaca na boca os citrinos e os frutos de caroço. Uma acidez equilibrada com um toque de doçura.',
      },
      {
        id: 29,
        name: 'Cabo da Roca Verdelho',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/verde%20cabo%20da%20roca%20verdelho.png?raw=true',
        price: 318,
        description:'Branco frutado e vibrante um blend de uvas 45% verdelho, 30% arinto e 25% fernão pires. De cor limão e aromas florais, de frutas brancas e notas citricas. sabores de pera, limão e maracujá, são apreciados no paladar. tem um final fresco e elegante.',
      },
      {
        id: 30,
        name: 'Chá Verde Salton',
        imageUrl: 'https://github.com/AndersonSantosFernandes/wineList/blob/main/verde%20moscato%20limao%20siciliano.png?raw=true',
        price: 18,
        description:'Chá verde feito de uvas Moscato, limão siciliano e erva cidreira, produzido na Vinícula Salton. Sem teor alcóólico.',
      },
    ],
  },
];